### ISSUE TITLE
[HELP]jhipster-registry's springCloudConfig with the git does not work

### ISSUE THREAD

**Issue by anjia0532** [jhipster/jhipster-registry#103]
jhipster-registry's version is 2.6.0

`src/main/resources/config/application-prod.yml`

```yaml
spring:
    profiles:
        active: prod
    cloud:
        config:
            server:
                #native:
                    #search-locations: file:./central-config
                git:
                    uri: https://github.com/spring-cloud-samples/config-repo
                prefix: /config
```

`export SPRING_PROFILES_ACTIVE=prod,native,swagger && ./mvnw` it's successful

output

```bash
----------------------------------------------------------
	Application 'jhipster-registry' is running! Access URLs:
	Local: 		http://127.0.0.1:8761
	External: 	http://xx.xx.xx.xx:8761
	Profile(s): 	[prod, native, swagger]
----------------------------------------------------------
```

![nothing.png](https://ooo.0o0.ooo/2017/03/24/58d4cc0e6ac38.png)

<kbd>Ctrl</kbd>+<kbd>C</kbd> stop the server

`git clone https://github.com/spring-cloud-samples/config-repo`

change the `src/main/resources/config/application-prod.yml`

```yaml
spring:
    profiles:
        active: prod
    cloud:
        config:
            server:
                native:
                    search-locations: file:./config-repo
                #git:
                    #uri: https://github.com/spring-cloud-samples/config-repo
                prefix: /config
```
it's ok 

![ok.png](https://ooo.0o0.ooo/2017/03/24/58d4cc0e804f3.png)

and the [foo-db.properties](https://github.com/spring-cloud-samples/config-repo/blob/master/foo-db.properties) 

[Jhipster - Application configuration with the JHipster Registry](https://jhipster.github.io/microservices-architecture/#-application-configuration-with-the-jhipster-registry)

##### **JHipster Version(s)**

```
gateway@0.0.0 /home/xxx/gateway
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.9
├── UNMET PEER DEPENDENCY @angular/core@2.4.9
├── generator-jhipster@4.1.1 
└── UNMET PEER DEPENDENCY zone.js@0.8.2

```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.shunneng.gateway",
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "4.1.1",
    "baseName": "gateway",
    "packageName": "com.shunneng.gateway",
    "packageFolder": "com/shunneng/gateway",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v7.6.0

npm: 4.1.2

yeoman: 1.8.5

yarn: 0.20.3
