### ISSUE TITLE
[BUG]`./mvnw -Pprod` is invalid

### ISSUE THREAD

**Issue by anjia0532** [jhipster/jhipster-registry#104]
```bash
./mvnw -Pprod

#output

----------------------------------------------------------
	Application 'jhipster-registry' is running! Access URLs:
	Local: 		http://127.0.0.1:8761
	External: 	http://xxx:8761
	Profile(s): 	[native, dev]
----------------------------------------------------------
#mvn -Pprod is invalid too
```
but `export SPRING_PROFILES_ACTIVE=prod,native,swagger && ./mvnw` it's ok

```bash
----------------------------------------------------------
	Application 'jhipster-registry' is running! Access URLs:
	Local: 		http://127.0.0.1:8761
	External: 	http://xxx:8761
	Profile(s): 	[prod, native, swagger]
----------------------------------------------------------

```

this way from the https://github.com/jhipster/jhipster-registry/blob/master/src/main/docker/dev/Dockerfile#L13

##### **JHipster Version(s)**

```
jhipster-registry@2.5.8 /home/xxx/jhipster-registry
└── generator-jhipster@3.4.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.0",
    "baseName": "jhipsterRegistry",
    "packageName": "io.github.jhipster.registry",
    "packageFolder": "io/github/jhipster/registry",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "useSass": false,
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "serverPort": "8761",
    "jwtSecretKey": "xxx"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v7.6.0

npm: 4.1.2

yeoman: 1.8.5

yarn: 0.20.3
