### ISSUE TITLE
jhipster-registry not support git config

### ISSUE THREAD

**Issue by anjia0532** [jhipster/jhipster-registry#123]
`docker-compose.yml`

```yml
version: '2'
services:
    jhipster-registry:
        image: jhipster/jhipster-registry:v2.6.0
        #volumes:
        #    - ./central-server-config:/central-config
        # By default the JHipster Registry runs with the "prod" and "native"
        # Spring profiles.
        # "native" profile means the filesystem is used to store data, see
        # http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - GIT_URI=https://github.com/jhipster/jhipster-registry/
        ports:
            - 8761:8761
```

the [application-dev.yml#L64](https://github.com/jhipster/jhipster-registry/blob/master/src/main/resources/config/application-dev.yml#L64)
```yml
spring:
    profiles:
        active: dev
        include: native #?maybe  should comment this?
```
the [config/config.controller.js#L26](
https://github.com/jhipster/jhipster-registry/blob/master/src/main/webapp/app/config/config.controller.js#L26)
```javascript
function load () {
            ProfileService.getProfileInfo().then(function (response) {
                vm.activeRegistryProfiles = response.activeProfiles;
                vm.isNative = vm.activeRegistryProfiles.includes('native'); // the vm.isNative allways true
                vm.nativeSearchLocation = response.nativeSearchLocation;
                vm.gitUri = response.gitUri;
                vm.gitSearchLocation = response.gitSearchLocation;
            });
        }
```
the [config/config.html#L32-L40](https://github.com/jhipster/jhipster-registry/blob/master/src/main/webapp/app/config/config.html#L32-L40)
```html
        <tr ng-if="vm.isNative" >
            <td>Native (Local Filesystem)</td>
            <td>{{ vm.nativeSearchLocation }}</td>
        </tr>
        <tr ng-if="!vm.isNative" > <!-- never show -->
            <td>Git</td>
            <td>{{ vm.gitUri }}</td>
            <td>/{{ vm.gitSearchLocation }}</td>
        </tr>
```
