### ISSUE TITLE
git Repository for Registry

### ISSUE THREAD

**Issue by sklakken** [jhipster/jhipster-registry#260]
I would like to solely use the Registry docker image as is generated. The search-locations, however, appears to be hard-coded into the system because it's set in bootstrap-prod.yml. If I simply comment the key properties as illustrated below in the source code, perform a prod build, and run, I'm able to override the default settings and reach my git repository. But what I need is to simply override the git properties in docker-compose using the provided image to setup my config server to point to the gitlab repo (no source code modifications). Please advise...

Just as a suggestion, I think the config server properties should be placed in the application-prod.yml file - not bootstrap-prod.yml, as the reasoning isn't apparent to me. :)

bootstrap-prod.yml (commented git settings)
```
spring:
    application:
        name: jhipster-registry
    profiles:
        active: prod,git
    cloud:
        config:
            server:
#                git:
#                    uri: https://github.com/jhipster/jhipster-registry-sample-config
#                native:
#                    search-locations: file:./central-config
                prefix: /config
                bootstrap: true
            fail-fast: true
            # name of the config server's property source (file.yml) that we want to use
            name: jhipster-registry
            profile: prod # profile(s) of the property source
            label: master # toggle to switch to a different version of the configuration as stored in git
            # it can be set to any label, branch or commit of the config source git repository
```
jhipster-registry.yml with gitlab settings:

```
version: '2'
services:
    jhipster-registry:
        image: jhipster/jhipster-registry:v3.2.4
        volumes:
            - ./central-server-config:/central-config
        # When run with the "dev" Spring profile, the JHipster Registry will
        # read the config from the local filesystem (central-server-config directory)
        # When run with the "prod" Spring profile, it will read the configuration from a Git repository
        # See http://www.jhipster.tech/microservices-architecture/#registry_app_configuration
        environment:
            - SPRING_PROFILES_ACTIVE=prod,git,swagger
            - SECURITY_USER_PASSWORD=admin
            - JHIPSTER_REGISTRY_PASSWORD=admin
            # - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/localhost-config/
            - GIT_URI=https://gitlab.com/...
            # - GIT_SEARCH_PATHS=central-config
            - SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME=username
            - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=password
        ports:
            - 8761:8761
```

**Comment by jdubois** [comment]
I'm not sure I understand your issue - you can override them using the standard Spring Boot mechanisms, typically I would use environment variables set up in Docker

**Comment by ruddell** [comment]
The purpose of bootstrap.yml is to load the config from an external config server, that's why the config  server URL is declared there.  See the [Spring Cloud docs](https://cloud.spring.io/spring-cloud-static/spring-cloud-commons/2.0.0.M9/multi/multi__spring_cloud_context_application_context_services.html)

Like Julien mentioned, you can override any config variables with environment variables through Docker.  The [Spring Boot docs on config loading order](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html) shows that an app loads environment variables before YML files).  

I've personally used an external Gitlab git repository with a custom search path declared through Docker environment variables using v3.2.4 of the registry, so I think you have an issue with your config (maybe uncomment `GIT_SEARCH_PATHS` and set it correctly).

**Comment by sklakken** [comment]
I've been doing Spring Boot/Config Server for a while now. The typical way an application is setup is by having a config server defined in the bootstrap.yml properties as is the case with the way JHipster is currently setup. Ok... However, because it's in a bootstrap file, the properties cannot be overridden as would be the case in an application properties file. Thus, when trying to override properties using a docker-compose.yml file for the jhipster/jhipster-registry   v3.2.4  image, the registry server reverts to the file:./central-config config. 

I've been wrong before... So, if anybody is able to provide me with a docker-compose.yml file that runs the registry with my gitlab repo (of course I'll have to privately enter the username/password), I'll donate $25 to JHipster. If not, I'll donate $10 anyway because I appreciate your work!

**Comment by PierreBesson** [comment]
It's true that you can overwrite all properties with env vars. But similarly to @sklakken I think it's bad that we have a hardcoded git configuration that is shipped in our Docker image. I just had some problems with it the other day doing a kubernetes demo.
And I think I was the one who coded this initially so I definitely understand why it is setup the way it is but it's still confusing anyway.

**Comment by ruddell** [comment]
@sklakken Sorry I should have posted my config before.  I just tested the following docker-compose file and it successfully clones the remote config and displays it in the UI.  I tested with supplying the username/password and also using the SSH option.  Lastly, I changed the repo to "public" so you can see what it looks like (same as the default example). 

```
version: '2'
services:
  registry:
    image: jhipster/jhipster-registry:v3.2.4
    ports:
      - 8761:8761
    environment:
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - SECURITY_USER_PASSWORD=admin
      - GIT_URI=https://gitlab.com/ruddell/config-sample.git
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - GIT_SEARCH_PATHS=central-config 
      - SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME=user
      - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=password
```
