### ISSUE TITLE
it seems 'application-prod.yml'  didn't work

### ISSUE THREAD

**Issue by ismjt** [jhipster/jhipster-registry#288]
##### **Overview of the issue**

after clone this repo, execute ```yarn install```, and config the following  section, 
```
security:
        user:
            name: admin
            # password's value is 123 in application-dev.yml
            # password's value is 456 in application-prod.yml
            password: 456
```

then running this project by ```./mvnw -Pprod```, 
only password 123 can login success

##### **Motivation for or Use Case**

wanna enable configurations in application-prod.yml 

##### **Reproduce the error**

1.  ```git clone https://github.com/jhipster/jhipster-registry.git```
2. ```cd jhipster-registry```
3. ```yarn install```
4. ```cd src/main/resources/config```
5. edit spring.security.user.password's value in application-dev.yml and application-prod.yml  file, such as:
```vim application-dev.yml```, change password to 123
```vim application-prod.yml```, change password to 456
6. ```cd ../../../../``` to this project's root directory
7. ```./mvnw -Pprod```

as a result, i can't login with password '456'.

even if i change the spring section in application-dev.yml, i get the same situation.
```
profiles:
        active: prod
        include: swagger
```

It's there anything wrong?

##### **JHipster Registry Version(s)**

  "version": "4.0.0",

##### **Browsers and Operating System**

Win10

- [ ] Checking this box is mandatory (this is just to show you read everything)
