### ISSUE TITLE
Unable to Use OIDC

### ISSUE THREAD

**Issue by sklakken** [jhipster/jhipster-registry#315]
I've successfully configured the JHipster Registry with Keycloak before sometime around April of this year. Coming back to it, it's not working out of the box. There are two primary issues:

1. When using the keycloak.yml docker-compose configuration, when linking to the "client" menu item, keycloak goes into a loop that constantly refreshes the screen. Therefore, I can't review the client setup. Later versions of keycloak don't have this behavior.

2. When successfully logging in, I get the following message that cannot be cleared: 

```
Your request cannot be processed :(
Sorry, an error has occurred.

Status:  (Unauthorized)
Message: Unauthorized
Other things to try:
Search localhost:8761:
```
I'm using the following docker-compose files:

keycloak.yml (embedded in the jhipster-registry source code)

```
version: '2'
services:
  keycloak:
    image: jboss/keycloak
#    image: jboss/keycloak:3.3.0.CR2-3
    command: ["-b", "0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config", "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING", "-Djboss.socket.binding.port-offset=1000"]
    volumes:
      - ./realm-config:/opt/jboss/keycloak/realm-config
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 9080:9080
      - 9443:9443
      - 10990:10990
```
docker-compose.yml 

```
version: '3'
services:
  registry:
    image: jhipster/jhipster-registry
    container_name: jhipster-registry
    hostname: jhipster-registry
    environment:
      - SPRING_PROFILES_ACTIVE=prod,swagger,oauth2
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - SECURITY_USER_PASSWORD=admin
      - SECURITY_OAUTH2_CLIENT_SECRET=2aaec15f-5c13-464a-bd58-555d79c3f97e

    ports:
      - 8761:8761
```
*Note: the client secret is grabbed from the registry-server client config
