### ISSUE TITLE
Micro service routes are still being registered in zuul for services filtered in consul

### ISSUE THREAD

**Issue by somejavadev** [jhipster/jhipster-registry#323]
#### **JHipster Info**

[jhipster-info.txt](https://github.com/jhipster/jhipster-registry/files/2765193/jhipster-info.txt)

##### **Overview of the issue**

Micro service routes are still being registered in zuul for services limited in consul via the ```default-query-tag``` property.

##### **Motivation for or Use Case**

I do not want all the services registered in consul to be listed and registered in my micro service gateway. To do this I have configured the ```default-query-tag``` for my gateway and applied the same tag (test) for the services I want to have registered:

##### **Reproduce the error**

I have configured my gateway and micro service with a "test" tag, one micro service without the tag.

Gateway:
```
    cloud:
        consul:
            discovery:
                tags: profile=${spring.profiles.active}, version=${info.project.version:}, test
                default-query-tag: test
```

Microservice 1:
```
    cloud:
        consul:
            discovery:
                tags: profile=${spring.profiles.active}, version=${info.project.version:}, test
```

Microservice 2:
```
    cloud:
        consul:
            discovery:
                tags: profile=${spring.profiles.active}, version=${info.project.version:}
```

When I navigate to my Swagger API at http://localhost:8080/#/admin/docs the dropdown with routes contains micro service 1 and 2, I would expect that micro service 2 should not be in the routes lists since it has been "filtered" out with the consul tag provided.

##### **Suggest a Fix**

The GatewaySwaggerResourcesProvider.java class calls routeLocater.getRoutes(), all routes are returned here. I would believed that the same filtering mechanism used for the consul service should have prevented the route from being registered in this list.

##### **JHipster Registry Version(s)**

Consul v1.1.0
Jhipster 5
Also see attached jhipster-info.txt

##### **Browsers and Operating System**

Ubuntu 18.04 64bit
Chrome/Firefox, this is not browser specific.

- [X ] Checking this box is mandatory (this is just to show you read everything)
