### ISSUE TITLE
Jhipster registry unable to fetch configuration from Cloud foundry nodes

### ISSUE THREAD

**Issue by jdevhari** [jhipster/jhipster-registry#333]
##### **Overview of the issue**

When Jhipster application is deployed into Cloud foundry on multiple instances, jhipster is unable to fetch the configuration or health details from specific nodes. 

I have configured the instance id as 
```
eureka:
    instance:
        hostname: ${vcap.application.uris[0]}
        instanceId: ${vcap.application.application_id}:${vcap.application.instance_index}
```
However as per cloud foundry documentation [here](https://docs.cloudfoundry.org/concepts/http-routing.html#app-instance-routing), unless I set the instanceId value defined above in the X-CF-APP-INSTANCE header, the traffic will not be routed to the correct instance.

- [X ] Checking this box is mandatory (this is just to show you read everything)
