### ISSUE TITLE
Enable use of a ssh git configuration source with docker

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-registry#41]
I have managed to make the registry's docker image use a ssh git configuration source. This only works with docker. It takes advantages of a feature provided by Spring Cloud Config that uses the local ssh keys in `~/.ssh`.

* install openssh (this should be added to the Dockerfile): `apk update && apk add openssh`

Those are the setup instruction that should be added to the docs, they need to be done only the first time.
* Go inside the container: `docker-compose exec jhipster-registry sh`
* Generate keys: `ssh-keygen`
* Copy the content public key in `/root/.ssh/id_rsa.pub` to remote git repo (for example in github settings)
* Test the ssh connection: `ssh -T git@github.com`
* Reply `yes` to add the git repo host to the list of known hosts:
```
The authenticity of host 'github.com (192.30.252.131)' can't be established.
Are you sure you want to continue connecting (yes/no)? 
```
* Restart the registry **without removing the container**, then it should be able to read a git repo secured by ssh.

Then, in order not to lose our setup every time we recreate or update the container, we can mount the `/root/.ssh/` folder to a docker volume (I'm not really sure of the security implications of this but if it's on the same machine it should be alright).

In the end I use this docker-compose file
**jhipster-registry-git.yml**
```
version: '2'
services:
    jhipster-registry:
        container_name: jhipster-registry
        image: jhipster/jhipster-registry
        volumes:
            - ./ssh/:/root/.ssh/
        environment:
             - SPRING_PROFILES_ACTIVE=prod
             - GIT_URI=ssh:git@github.com:PierreBesson/test-registry.git
        ports:
            - 8761:8761
```

You can also mount your own `~/.ssh` instead of a `./ssh` subdirectory to have it work out of the box with your repos.
