### ISSUE TITLE
Peer Awareness

### ISSUE THREAD

**Issue by krishnaarava** [jhipster/jhipster-registry#45]
I am trying to setup peer awareness in application.yml using the below configuration but I when I start the server dont see any logs trying to ping the "peer" host. Per the configuration this should be showing a lot of chatter http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html. Am I missing something here. 

```
eureka:
    instance:
        appname: registry
        hostname: localhost
        prefer-ip-address: true
    server:
        enable-self-preservation: true
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://peer2/eureka/
```

**Comment by krishnaarava** [comment]
I found the solution and it was working after I removed few attributes. Below is the updated configuration

```
eureka:
    instance:
        appname: registry
        hostname: localhost
        prefer-ip-address: true
    server:
        enable-self-preservation: true
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://peer2/eureka/
```
