### ISSUE TITLE
Does JHipster Registry supports private access token on github.com?

### ISSUE THREAD

**Issue by FABH** [jhipster/jhipster-registry#506]
As github.com password authentication is not available anymore, does JHipster Registry supports private access token on github.com?

**Comment by juliensadaoui** [comment]
By default, the JHipster Registry uses the SSH configuration files. Instead of use SSH, you can use Token authentication on the remote repository.

What you need to do, it is create a personal access token from the Github console. 

- login in your gitHub folow this path: Settings > Developer settings > Personal access tokens > Generate new token
- set a long time to expiration token, check the "repo" to allow access repository with this token, and Generate token.
- configure your spring configuration server, this is a content of file "bootstrap-prod.yml" of spring configuration server at path /src/main/resources/config/bootstrap-prod.yml.

```
spring:
  cloud:
    config:
      server:
        bootstrap: true
        composite:
          - type: git
            uri: https://github.com/jhipster/jhipster-registry-sample-config
            username=<yourusername>
            password=<yourtoken>
```
