### ISSUE TITLE
registry v7.3.0 not showing metrics for oauth stateful microservices

### ISSUE THREAD

**Issue by fabioportieri** [jhipster/jhipster-registry#573]
##### **Overview of the issue**

i'm running an instance of jhipster registry in which several microservices are connected, including a gateway with angular frontend

i can see the metrics fine if i connect directly to my frontend but i expect to see metrics from the registry dashboard, but on the "administrator" menu only the submenu "api" is shown, and i see a weird error on chrome console

979.a1e9c1b0f9adf531.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'params')
    at 979.a1e9c1b0f9adf531.js:1:93570

pointing to this code:
```
    this.accountService.identity().subscribe(),
                    this.router.events.subscribe(z=>{
                        if (z instanceof Kt.R9) {
                            const Y = z.state.root.firstChild.children[0]
                              , he = Y.params   // <------ error here
```

##### **Reproduce the error**

i run the registry with the following docker compose entry:

```

  jhipster-registry-1:
    image: jhipster/jhipster-registry:v7.3.0
    hostname: jhipster-registry-1
    volumes:
      - ./central-server-config:/central-config
    environment:
      - SPRING_PROFILES_ACTIVE=dev,api-docs,oauth2
      - SPRING_SECURITY_USER_PASSWORD=PASS
      - JHIPSTER_REGISTRY_PASSWORD=PASS
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=URI
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=CLIENT_ID
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=SECRET
    ports:
      - 8761:8761
    networks:
      csg_net:
        aliases:
          - jhipster-registry-1
```

it connects to an on premise keycloack instance, as they do all the microservices

any pointer in how to debug this?
Thanks in advance

##### **JHipster Registry Version(s)**

v7.3.0

##### **Browsers and Operating System**
all versions
